language: ruby
rvm:
- 2.6.3
services:
- postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
install:
- bundle install
- bundle exec rails db:create
- bundle exec rails db:migrate
before_script:
  - cp config/database.yml
script:
- bundle exec rspec
secure: U4BTQzX6eImeKd2ehNQFuBfqgN3L4FK8KrNskWyAdaF+RFdiOWR102GMiF2qNa/igBiBEMFb4OVTlis7DOIcg4FVFe40ZDKUXaCjp4Za/K79y6wh5LqrFONNMRxcGGO/+zd0WhPVozkh/Ani3d75BAP8bqAXZeZl0if/RxN2vubXaiRW5XQ6l9WZBZgxZ4ruiq/XDplBABxO+8g2+2DZGuKXglB2cXFMUMkkgWF0TsU3XyIrs+5WMSevZNAxkGX8dY6FkN3ZEryR3oVA+4HH34VGv+s9bnyc+3dlKq5bfE1uHgERxGQonolkYmjwGQXp6FDWzHe3vhY4oLiLKFwxZyxOrBhaZl5ORKYep9hVl3CTBz7AbUa+sFyFZ3nm7MTSuelri4m4AgoVNqNI7HfxMxMD9qExAx6EbBt1bz8pAHmqMq7gSeG7/Lu5FabkyHIrXcmBGPKt6o44WZhHP6Iuvn6RuJ93byyzzubUBjgFO1yzIBAKPRJeqTu4lGbq73gysWVVzNJ3fAnExd3wVwWJ6qB5wc1olg5nV5gONsDR/K8HYAiNO3JYh+htADKO/XLGlwfgRehdFBaEgI/uIIC673Yt8aVQfWB6wPATzkirhh1wBuK0FiuJUvK/QsViNEsoJB5ModY5SiYL52QNqDWkUXDTD+aB2ihha98Gv8J6AzY=
env:
  global:
  - PGPORT=5433
  - secure: d/nkHrVuaDrTGNDq6bMqpFtjAhMxqp6o7STb8hEn2lEZoZFKZA4KLBCNlHCuSjsZK+py4huNkajqwgwistTbChFnghHkmJbx1YzPhXjSB9PlrZtsb2E67S6iPJuhJyzPp9K84O6tlzYpqoGJCtJf/zEeL1bkBKMmCfuTsbExnbZ/ut1hF4egTbXcPvhomFH+sGR6Ly0ZO4RkCnQNFLrnQC/aeIN+bXs0EcCyKk+sUXsmJC644kNvuIldGCRQDghJpG1d13mzo3maoz/qXuBhBGablnNSQHYGLZeWSxScP7kn8uZPsbQ63JsJEO5LI8XBYpan6ntdAOXY0lQheHt5zoobjstZutrEvRCrZ4oCR+03enqskNOM7R726YFVR6O0Z+btzW0MEMmGdc7eE6s0ev6lA8CqexCaBwSFPYYeFc44B1nSz++FIRDaLq3WWuS9ahRRAQ0kZnWzqil3v1x8d7lTS1J7MNFNXD+DPTFCEi3xikbBchcczPoXgYA8mEywY5lYHhChL+rMmzoJ3tuuYq4LeJCfb0sFRG4jRwdJkdHVFwBmYeb1H84+N6JR61UCBoXz7RMiRZSescSVRWGKZWN1n4OSdAj1+60CYLn0R2tJFzWUq+dF0L0tfGpSaMSoYOcjCThbMNz6K35blfCFftBKiV49ZTVu07c0prtwXJc=
  - secure: O22qoZ4OC7F9wn7H0rhGHCb90orXNC6+IZFiuNe17SCwj8yC1Mu0ae/OX1cknHC6Mf81tgdtLTt9aNbMg8/ePF6JaIeeLcX6VbhgsN0Tvjt8r1ebH3Yf3tME2+Tc7ku3jk9tUaT2TWZunp/j0jjyCPhIEqJ8TABgeNbUJ1K36QEMmiS9WbO7SwytCucAyYi04nkwhWLdS5+aQ7ieklcBqCsRW2ktGq9+oAfJS/o1LIqNu2QrQ0L0o0Ei7d7ADGDwks5ZsqAkrIQ4sRTQbLK0qFMYVSYzn4HEYzEvflxAGGSp8w87pYHBbaVNLl0NwfEK/J39L+1l34srv9iWTFTt3uCN9OeLo4j55Pb9uqtBpVcI80iS1r0Gyo1PyQkPBvTIPjA/XtnqytQD+wRddHQe0jMGJMQbf7WjUpaNaMJyaoERYn8yCUxLy8WMMAM9rXWktLmmH4fXLw0Pj6s5QjmRH7IKV94Ihy5k5HTBmqJ36loEfA81v406D6TMZAPA01qE5MCdfVqbjp5R4/0XPX/sLnhVhQGmDNU+IoqgoG+AarwPrp1HMBCK3sDD4j2MC4oiYWgUtxNkYStDqwQBjvngfISVecTy9r08nEPm2l/mE2k+rB34/Vl+Av7qfLAeEyHpH2r3dDqoMcg0+BxylqocDWLd6HJeaw0/kbR+Av7voJU=
