language: ruby
rvm:
  - 2.5.0

services:
  - postgresql

# before_install:
#   - gem update --system
#   - gem install bundler

install:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate

script:
  - bundle exec rspec
