language: ruby
rvm:
  - 2.6.3

services:
  - postgresql

# before_install:
#   - gem update --system
#   - gem install bundler

install:
  - bundle install
  - bundle exec rails db:create
  - bundle exec rails db:migrate

script:
  - bundle exec rspec

secure: "T+2OeOWTmlERCzvlXyueGr6vFokxAOpYl++aidb9XI9ijf4Ew/RBcywzNT0mkIvG7zAyWEYJGVZX/QYQjK2KmhcE49m+ufHKZJQGwXo9ZHb4n1J8nNhoqbonuDl7P0UzHgKkyKaSxN9i/2WE70kosmxGPOYNsz93v8rMRchigcfMIW32u5HpSd0MezEkZ3t3F4pTpnPBR1VTXAsQjkOgKCLfEdNKpiVHbO15pPlyrcs7ZOS80emP/yuPKKGxuJD+g8/0hzBbzx80pQMtCmJFTr0LYHxehWwqVi6ZjlWNwD+6krZKDbVVq+rFh61mbZA3wGsL2snjQT12PbVeKYWRhDOpSaVpOnvNQgjS3oLqKBGBvZexAABZYVVTKsAFfEqcIbpEmWlT66Cxo1byEHk2JyHB2pyqMaA29VA3qHhejsRoNslxR6q+Tk2cU8gVj4bpiXMnX4s9hsldWh53kclUbIRThPs6s/S075HrgD4hvO3sJrvVNrmXPiT4Gx2fBHjL0DOaMz70+uQb3NK/+C7M8sWvAojr6L4D3k0Qa/z8r1cL9SNz1ITezYhdleEFXKSgVe4I0ecdRxBHSQY9Z4iltOtL4SYcpeAa9gDb3IIOLKK3peBlp+v8B0LjsY/AExURCpJghhBbWJ6Yuc9mzVb1j2xeo8+VFAYTvvRioEcaR6Q="

secure: "U4BTQzX6eImeKd2ehNQFuBfqgN3L4FK8KrNskWyAdaF+RFdiOWR102GMiF2qNa/igBiBEMFb4OVTlis7DOIcg4FVFe40ZDKUXaCjp4Za/K79y6wh5LqrFONNMRxcGGO/+zd0WhPVozkh/Ani3d75BAP8bqAXZeZl0if/RxN2vubXaiRW5XQ6l9WZBZgxZ4ruiq/XDplBABxO+8g2+2DZGuKXglB2cXFMUMkkgWF0TsU3XyIrs+5WMSevZNAxkGX8dY6FkN3ZEryR3oVA+4HH34VGv+s9bnyc+3dlKq5bfE1uHgERxGQonolkYmjwGQXp6FDWzHe3vhY4oLiLKFwxZyxOrBhaZl5ORKYep9hVl3CTBz7AbUa+sFyFZ3nm7MTSuelri4m4AgoVNqNI7HfxMxMD9qExAx6EbBt1bz8pAHmqMq7gSeG7/Lu5FabkyHIrXcmBGPKt6o44WZhHP6Iuvn6RuJ93byyzzubUBjgFO1yzIBAKPRJeqTu4lGbq73gysWVVzNJ3fAnExd3wVwWJ6qB5wc1olg5nV5gONsDR/K8HYAiNO3JYh+htADKO/XLGlwfgRehdFBaEgI/uIIC673Yt8aVQfWB6wPATzkirhh1wBuK0FiuJUvK/QsViNEsoJB5ModY5SiYL52QNqDWkUXDTD+aB2ihha98Gv8J6AzY="
